# Generated by Django 5.1.3 on 2024-11-24 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='LunaMeetSite.category')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.event')),
            ],
        ),
        migrations.CreateModel(
            name='Organizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.event')),
            ],
        ),
        migrations.CreateModel(
            name='Planed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.event')),
            ],
        ),
        migrations.CreateModel(
            name='TimeCod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_cods', to='LunaMeetSite.event')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('commented_events_id', models.ManyToManyField(related_name='commented_users', through='LunaMeetSite.Comments', to='LunaMeetSite.event')),
                ('organized_events_id', models.ManyToManyField(related_name='organized_event', through='LunaMeetSite.Organizers', to='LunaMeetSite.event')),
                ('planed_events_id', models.ManyToManyField(related_name='planed_users', through='LunaMeetSite.Planed', to='LunaMeetSite.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='planed',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.user'),
        ),
        migrations.AddField(
            model_name='organizers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='commented_users_id',
            field=models.ManyToManyField(related_name='commented_events', through='LunaMeetSite.Comments', to='LunaMeetSite.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizers_id',
            field=models.ManyToManyField(related_name='organized_events', through='LunaMeetSite.Organizers', to='LunaMeetSite.user'),
        ),
        migrations.AddField(
            model_name='event',
            name='planed_users_id',
            field=models.ManyToManyField(related_name='planed_events', through='LunaMeetSite.Planed', to='LunaMeetSite.user'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.user'),
        ),
        migrations.CreateModel(
            name='Visited',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LunaMeetSite.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='visited_events_id',
            field=models.ManyToManyField(related_name='visited_users', through='LunaMeetSite.Visited', to='LunaMeetSite.event'),
        ),
        migrations.AddField(
            model_name='event',
            name='visited_users_id',
            field=models.ManyToManyField(related_name='visited_events', through='LunaMeetSite.Visited', to='LunaMeetSite.user'),
        ),
    ]
