# Generated by Django 5.1.3 on 2024-11-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMeetSite', '0002_user_groups_user_is_active_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photo',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
