# Generated by Django 5.1.3 on 2024-11-27 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMeetSite', '0005_event_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='timecod',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_codes', to='LunaMeetSite.event'),
        ),
    ]
