# Generated by Django 5.1.3 on 2024-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMeetSite', '0006_event_place_alter_timecod_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=400),
        ),
    ]
