# Generated by Django 5.1.3 on 2024-11-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMeetSite', '0007_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icons/'),
        ),
    ]
