# Generated by Django 5.1.3 on 2024-11-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMeetSite', '0008_user_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reg_link',
            field=models.URLField(default=''),
        ),
    ]
