# Generated by Django 5.1.3 on 2024-11-29 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LunaMeetSite', '0009_event_reg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='reg_link',
            field=models.URLField(blank=True),
        ),
    ]
